site_name: SIPx 开发说明
site_author: 广州市和声信息技术有限公司
copyright: |
  <a href="http://www.hesong.net/" target="_blank">广州市和声信息技术有限公司</a> © 2022

docs_dir: src
custom_dir: overrides

# 目录
nav:
  - index.md

  - docs/quick-start.md

  - API 使用:
      - 腾讯云 TRTC:
          - docs/trtc/index.md

      - 阿里云音视频通信 RTC:
          - docs/aliyunrtc/index.md

extra:
  generator: false

theme:
  name: material
  language: zh
  font: false
  favicon: images/favicon.png
  icon:
    logo: material/webrtc

  features:
    - header.autohide
    # - navigation.instant
    - navigation.sections
    # - navigation.expand
    # - navigation.tabs
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - content.tooltips

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 切换到暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 切换到亮色模式
      primary: teal
      accent: teal

markdown_extensions:
  # Officially Supported Extensions
  - abbr
  - admonition
  - meta
  - sane_lists:
  - smarty:
  - toc:
      permalink: true
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
  - pymdownx.extra
  ### pymdownx.extra replaces markdown.extensions.extra, Here is the full list of included extensions:
  ## pymdownx.betterem
  ## pymdownx.superfences
  ## markdown.extensions.footnotes
  ## markdown.extensions.attr_list
  ## markdown.extensions.def_list
  ## markdown.extensions.tables
  ## markdown.extensions.abbr
  ## markdown.extensions.md_in_html
  ## 用不到公式
  # - pymdownx.arithmatex:
  #     generic: true
  - pymdownx.highlight:
      guess_lang: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets:
      auto_append:
        - includes/official_site.md
        - includes/abbreviations.md
  # 3rd extensions
  - plantuml_markdown:
      ## 如在 Windows 中无法使用 plantuml，可启用这个配置
      # server: http://www.plantuml.com/plantuml
      # format: svg

extra_javascript:
  - scripts/tabbedSync.js

plugins:
  - search
  ## with-pdf is Not available on Windows
  # - with-pdf:
  #     enabled_if_env: ENABLE_PDF_EXPORT
  #     toc_title: 目录
  #     toc_level: 3
  #     cover_title: SIPx
  #     cover_subtitle: 开发说明
