# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# 发布到 阿里云 OSS 静态站

name: Aliyun OSS Deploy

on:
  push:
    branches:
      - main

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          cache: pip

      - name: pip install
        run: pip install -r requirements.txt

      - name: Set up ALIYUN osstuil
        run: |
          wget https://gosspublic.alicdn.com/ossutil/1.7.13/ossutil64
          chmod 755 ossutil64
          ./ossutil64 --version
          echo "
          [Credentials]
          endpoint = ${{ secrets.ALIYUN_OSS_ENDPOINT }}
          accessKeyID = ${{ secrets.ALIYUN_API_KEY_ID }}
          accessKeySecret = ${{ secrets.ALIYUN_API_KEY_SECRET }}
          " | tee ~/.ossutilconfig

      - name: Build mkdocs
        run: |
          mkdocs build
        
      - name: Upload to ALIYUN OSS
        run: |
          ./ossutil64 cp -fr site oss://${{ secrets.ALIYUN_OSS_BUCKET }}/docs/develop-guide
