# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Serverless Deploy

on:
  push:
    branches:
      - main

jobs:
  serverless-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          cache: pip

      - name: pip install
        run: pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: npm install
        run: |
          npm install dotenv-cli
          npm install --location=global serverless

      - name: serverless deploy
        run: |
          serverless deploy
